/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import Icon1Image from './assets/images/Chevron_Icon.png';
import { styled } from '@mui/material/styles';
import { ChevronProps } from './types';

 
const DirectionLeft: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `16px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Icon1: any = styled("img")({  
  height: `16px`,  
  width: `9.44px`,  
  position: `absolute`,  
  left: `3px`,  
  top: `0px`,  
});
 
function Chevron(props: ChevronProps): JSX.Element {
  return (
    <DirectionLeft className={props.className} >
      <Icon1  src={Icon1Image} alt={"Icon"}/>
    </DirectionLeft>
  );
}

export default Chevron;
