/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import UnionImage from './assets/images/Union_1.png';
import { styled } from '@mui/material/styles';

 
const ArrowUp: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `16px`,  
  height: `16px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Group: any = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `8.5px`,  
  height: `5px`,  
  left: `4px`,  
  top: `10px`,  
});
  
const Union: any = styled("img")({  
  height: `5px`,  
  width: `8.5px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `-5px`,  
});
 
function Icons16PxExpanded(): JSX.Element {
  return (
    <ArrowUp >
       <Group >
         <Union  src={UnionImage} alt={"Union"}/>
       </Group>
     </ArrowUp>
   );
}

export default Icons16PxExpanded;
