/**********************************************************************
*
*   Types file generated by Quest
*
*   Types for the components props go in this file
*   To set up custom types for the components props, edit the corresponding types in this file
*   Once you edit a type to no longer by "any", be careful to not override it on your next export 
*   Verify diff before merging
*
*   For help and further details refer to: 
*   https://docs.quest.ai/react/fundamentals/exporting-code
*
*
**********************************************************************/

export interface AccordionsHelpersTopProps {
  state: any;
  onClick: any;
  title: any;
};

export interface AccordionsHelpersContentProps {
  content: any;
};

export interface AccordionsAccordionProps {
  title: any;
  content: any;
  testprop: any;
};