/**********************************************************************
*
*   Types file generated by Quest
*
*   Types for the components props go in this file
*   To set up custom types for the components props, edit the corresponding types in this file
*   Once you edit a type to no longer by "any", be careful to not override it on your next export 
*   Verify diff before merging
*
*   For help and further details refer to: 
*   https://docs.quest.ai/react/fundamentals/exporting-code
*
*
**********************************************************************/

export interface QuizViewerModuleProps {
  className?: any;
};

export interface ViewerQuestionTypeProps {
  className?: any;
  number: any;
  setCurrentAnswer: any;
  currentAnswer: any;
  completed: any;
};

export interface ProgressStepsProgressMinimalIcProps {
  className?: any;
  completed: any;
  current: any;
};

export interface ChevronProps {
  className?: any;
  direction: any;
};

export interface Button1Props {
  className?: any;
  onClick: any;
  completed: any;
  current: any;
  currentAnswer: any;
};

export interface StepBaseProps {
  className?: any;
  completed: any;
  active: any;
  number: any;
};

