/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { useState } from "react";

const useAccordianDemo = () => {

  const [items, setItems] = useState([
    {
      title: "Dynamic title 1",
      content: `Content 1`,
    },
    {
      title: "Dynamic title 2",
      content: `Content 2`,
    },
    {
      title: "Dynamic title 3",
      content: `Content 3`,
    },
    {
      title: "Dynamic title 4",
      content: `Content 4`,
    },
  ]);

  let data: any = {
    items
  };

  let fns: any = {};
  return {data, fns};
}

export default useAccordianDemo;