/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/
import React, { useState } from "react";
const useButton1 = () => {
  const [isActive, setIsActive] = useState(false);
  let data: any = {};
  data.isActive = isActive

  const setActive = (): any => {
    setIsActive(true);
  };
  
  const setInactive = (): any => {
    setIsActive(false);
  };

  let fns: any = {setActive, setInactive};
  return {data, fns};
}

export default useButton1;