/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/
import React, { useState } from "react";

const useQuizViewerModule = () => {
  const [currentQuestion, setCurrentQuestion] = useState<any>(1);
  const [completedQuestions, setCompletedQuestions] = useState<any>([]);
  const [currentAnswer, setCurAnswer] = useState(null);

  let data: any = {};

  data.currentQuestion = currentQuestion;
  data.completedQuestions = completedQuestions;
  data.currentAnswer = currentAnswer;

  const setCompleted = (param1: any): any => { 
    if (currentAnswer) {
      setCompletedQuestions((state: any) => {state.push(param1); return state});
      if (currentQuestion !== 4 ) {
        setCurrentQuestion((state: any) => state+1)
      }
      if (currentQuestion === 4) {
        setCurrentQuestion(null)
      }
      setCurAnswer(null)
    }
  };
  const setCurrentAnswer = (param1: any): any => {
    if (completedQuestions.length < 4)
    setCurAnswer(param1);
  };

  let fns: any = {setCompleted, setCurrentAnswer};
  return {data, fns};
}

export default useQuizViewerModule;