/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/
import React, { useState } from "react";

const useViewerQuestionType = () => {

  const [isHover, setIsHover] = useState(false);
  let data : any= {};
  data.isHover = isHover;
  const hoverOn = (): any => {setIsHover(true)};
  const hoverOff = (): any => {setIsHover(false)};

  let fns: any = {hoverOn, hoverOff};
  return {data, fns};
}

export default useViewerQuestionType;